spring.application.name=tcrs-backend
server.port=8080
spring.security.user.name=admin
spring.security.user.password=yourpassword
#for spring security dependency you should set those above


# for mongodb atlas
spring.mongodb.uri=mongodb+srv://vivek57yadav_db_tcrs:PositiveSir@cluster0.dr9fpji.mongodb.net/tcrs_db

# JWT config (you'll set a real secret in Phase 2)
jwt.secret=tcrs_super_secret_key_change_this_later
jwt.expiration=86400000