spring.application.name=tcrs-backend
server.port=8080
spring.security.user.name=admin
spring.security.user.password=yourpassword
#for spring security dependency you should set those above


# for mongodb atlas
spring.mongodb.uri=mongodb+srv://vivek57yadav_db_tcrs:PositiveSir@cluster0.dr9fpji.mongodb.net/tcrs_db

# JWT config (you'll set a real secret in Phase 2)
jwt.secret=tcrs_super_secret_key_change_this_later
jwt.expiration=86400000




# ── Email (Gmail SMTP for forgot password OTP) ──────────────────────────────
# Steps to set this up:
# 1. Go to your Gmail account settings
# 2. Enable 2-Factor Authentication
# 3. Go to "App Passwords" → generate a password for "Mail"
# 4. Paste that 16-char password below as spring.mail.password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vivek57yadav@gmail.com
spring.mail.password=dxlcxjjixmeexwhj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
 
# OTP expiry in minutes
otp.expiry.minutes=10
 
# App name shown in emails
app.name=TCRS